In [1]:
#Data engneering 
#numpy(creating arrays)

In [41]:
#import library
import numpy as np


In [3]:
#create a 1D numpy array with integer numbers from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#create 2D numpy array with shape (3,3) and fill it with zeros
np.zeros([3,3],'int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
#create 3D numpy array with shape (2,3,4) and fill it with ones
np.ones([2,3,4],'int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [13]:
##create a numpy array with 10 random integer numbers beween 0 to 100
np.random.randint(0,101,10)

array([ 16, 100,  23,  91,  84,  59,  23,  76,  28,  94])

In [16]:
#create a numpy array with 10 random float numbers beween 0 to 1
np.random.uniform(size = 10, low = 0, high = 1) 
np.random.rand(10)

array([0.32485564, 0.50954755, 0.76749977, 0.75762696, 0.08269174,
       0.60331096, 0.61032777, 0.40997726, 0.5808479 , 0.53926563])

In [25]:
#create a numpy array with 5 equally spaces between 0 ,1
np.arange(0,1.1,.25)
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
#create a numpy array with 5 equally spaces between 0 ,10
np.arange(0,11,2.5)
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
#create a numpy array with 5 equally spaces between -1,1
np.arange(-1,1.1,.5)
np.linspace(-1,1,num=5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [49]:
#create a numpy array with sine values of angle between 0 ,2PI
angle= np.linspace(0, 2*(np.pi), 10)
np.sin(angle)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [50]:
#create a numpy array with cosine values of angle between 0 ,PI
angle= np.linspace(0, np.pi, 10)
np.cos(angle)

array([ 1.        ,  0.93969262,  0.76604444,  0.5       ,  0.17364818,
       -0.17364818, -0.5       , -0.76604444, -0.93969262, -1.        ])