In [1]:
#scalar operations

In [2]:
import numpy as np

In [21]:
#1. Create a 2x2 NumPy array and multiply it by 2.
shape = (2, 2)
arr1=np.ones(shape)
arr1*2


array([[2., 2.],
       [2., 2.]])

In [20]:
#2. Create a 3x3 NumPy array and add 5 to each element.
shape = (3, 3)
arr2=np.ones(shape)
arr2+5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [18]:
#3. Create a 4x4 NumPy array and subtract 10 from each element.
shape = (4, 4)
arr3=np.ones(shape)
arr3-10

array([[-9., -9., -9., -9.],
       [-9., -9., -9., -9.],
       [-9., -9., -9., -9.],
       [-9., -9., -9., -9.]])

In [19]:
#4. Create a 5x5 NumPy array and divide each element by 2.
shape = (5, 5)
arr4=np.ones(shape)
arr/2

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [24]:
#5. Create a 6x6 NumPy array and calculate the square root of each element
shape = (6,6)
arr5=np.ones(shape)
np.sqrt(arr5)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#matrix product and multiplcation 

In [28]:
#6. Create two 2x2 NumPy arrays and calculate their product using the np.matmul() function
m1=np.array([[4,2],[2,5]])
np.matmul(arr1,m1)

array([[6., 7.],
       [6., 7.]])

In [29]:
#7. Create two 3x3 NumPy arrays and calculate their product using the np.dot() function.
m2=np.array([[4,2,7],[2,5,8],[7,0,3]])
np.dot(arr2,m2)

array([[13.,  7., 18.],
       [13.,  7., 18.],
       [13.,  7., 18.]])

In [30]:
#8. Create a 2x3 NumPy array and a 3x2 NumPy array, and calculate their product using the
np.matmul() function
m3=np.array([[4,2,7],[2,5,8]])
m4=np.array([[4,2],[2,5],[7,0]])
np.matmul(m3,m4)

array([[69, 18],
       [74, 29]])

In [31]:
#9. Create a 3x2 NumPy array and a 2x3 NumPy array, and calculate their product using the np.dot()function.
np.dot(m3,m4)

array([[69, 18],
       [74, 29]])

In [33]:
#10. Create a 4x4 NumPy array and its transpose using the np.transpose() function, then calculate their product using the np.matmul() function
m5=np.array([[4,2,1,5],[2,5,7,2],[7,0,2,1],[1,6,3,8]])
m5

array([[4, 2, 1, 5],
       [2, 5, 7, 2],
       [7, 0, 2, 1],
       [1, 6, 3, 8]])

In [34]:
np.transpose(m5)

array([[4, 2, 7, 1],
       [2, 5, 0, 6],
       [1, 7, 2, 3],
       [5, 2, 1, 8]])