In [20]:
#Data Engineering ,Numpy (Array Indexing)

In [3]:
import numpy as np

In [5]:
#1. Create a 1D NumPy array with the integers from 0 to 9. Extract the 3rd element from the array.
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a[2]

2

In [31]:
#2. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Extract the element at row 2, column 1.
b=np.random.randint(1,10,size=(3,3),dtype=int)
b

array([[5, 4, 9],
       [3, 9, 3],
       [9, 3, 7]])

In [32]:
b[1][0]

3

In [23]:
#3. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Extract the subarray consisting of the first 2 rows and the last 2 columns.
c=np.random.randint(1,10,size=(4,4),dtype=int)
c

array([[3, 6, 9, 5],
       [5, 3, 7, 4],
       [6, 8, 7, 9],
       [3, 8, 9, 2]])

In [26]:
c[:2,-2:]

array([[9, 5],
       [7, 4]])

In [30]:
#4. Create a 1D NumPy array with the integers from 0 to 9. Copy a slice of the array consisting of the first 3 elements
a[:3]

array([0, 1, 2])

In [34]:
#5. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy a slice of the array consisting of the first 2 rows and the first 2 columns.
b[:2,:2]


array([[5, 4],
       [3, 9]])

In [38]:
#6. Create a 1D NumPy array with the integers from 0 to 9. Reshape the array into a 2D array with shape (3, 3).
s=np.arange(9)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
s.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
#7. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Reshape the array into a 1D array.
c.reshape(1,16)

array([[3, 6, 9, 5, 5, 3, 7, 4, 6, 8, 7, 9, 3, 8, 9, 2]])

In [53]:
#8. Create two 1D NumPy arrays with the integers from 0 to 4. Concatenate the two arrays into a single 1D array
arr=np.arange(5)
np.concatenate((arr,arr))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [58]:
#9. Create two 2D NumPy arrays with shapes (2, 2) and (2, 3). Concatenate the two arrays horizontally.
arr1=c=np.random.randint(1,10,size=(2,2),dtype=int)
arr2=np.random.randint(1,10,size=(2,3),dtype=int)


In [61]:
arr1

array([[2, 1],
       [6, 4]])

In [62]:
arr2

array([[9, 3, 6],
       [2, 9, 6]])

In [63]:
np.hstack((arr1,arr2))

array([[2, 1, 9, 3, 6],
       [6, 4, 2, 9, 6]])

In [64]:
#10. Create two 2D NumPy arrays with shapes (2, 2) and (3, 2). Concatenate the two arrays vertically
arr1=c=np.random.randint(1,10,size=(2,2),dtype=int)
arr2=np.random.randint(1,10,size=(3,2),dtype=int)

In [65]:
arr1

array([[9, 6],
       [3, 3]])

In [66]:
arr2

array([[3, 1],
       [4, 4],
       [5, 2]])

In [67]:
np.vstack((arr1,arr2))

array([[9, 6],
       [3, 3],
       [3, 1],
       [4, 4],
       [5, 2]])

In [ ]:
#11. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Split the array into two equal horizontal halves.
