In [1]:
#Numpy (Universal Array Function)

In [2]:
import numpy as np

In [7]:
#1. Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.exp() function to compute the exponential of each element in the array.
arr=np.random.randint(1,100,size=(3,3),dtype=int)
arr

array([[ 4, 38,  7],
       [37, 56, 12],
       [94, 64, 30]])

In [8]:
np.exp(arr)

array([[5.45981500e+01, 3.18559318e+16, 1.09663316e+03],
       [1.17191424e+16, 2.09165950e+24, 1.62754791e+05],
       [6.66317622e+40, 6.23514908e+27, 1.06864746e+13]])

In [9]:
#2. Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.sin() function to compute the sine of each element in the array.
arr1=np.random.randint(1,100,size=(4,4),dtype=int)
arr1

array([[18, 96, 26, 59],
       [77, 85, 92, 69],
       [49, 88, 68, 54],
       [87,  6, 29, 95]])

In [10]:
np.sin(arr1)

array([[-0.75098725,  0.98358775,  0.76255845,  0.63673801],
       [ 0.99952016, -0.17607562, -0.77946607, -0.11478481],
       [-0.95375265,  0.0353983 , -0.89792768, -0.55878905],
       [-0.82181784, -0.2794155 , -0.66363388,  0.68326171]])

In [11]:
#3. Create a NumPy array with shape (5,5) and fill it with random numbers. Use the np.log() function to compute the natural logarithm of each element in the array
arr2=np.random.randint(1,100,size=(5,5),dtype=int)
np.log(arr2)

array([[3.55534806, 2.56494936, 4.52178858, 3.71357207, 3.97029191],
       [4.04305127, 1.79175947, 4.48863637, 1.94591015, 4.58496748],
       [3.87120101, 3.55534806, 4.02535169, 2.19722458, 3.55534806],
       [4.18965474, 4.27666612, 2.77258872, 4.35670883, 3.66356165],
       [4.47733681, 3.93182563, 2.89037176, 4.12713439, 4.47733681]])

In [12]:
#4. Create a NumPy array with shape (2,2) and fill it with random numbers. Use the np.sqrt() function to compute the square root of each element in the array
np.sqrt(np.random.randint(1,100,size=(2,2),dtype=int))

array([[6.8556546 , 7.54983444],
       [8.30662386, 9.74679434]])

In [15]:
#5. Create a NumPy array with shape (6,6) and fill it with random numbers. Use the np.floor() function to round down each element in the array to the nearest integer
np.floor(np.random.randn(6,6))

array([[-1., -1.,  1.,  1., -2., -1.],
       [ 0.,  0.,  1.,  0., -1., -2.],
       [ 0., -1., -1.,  0.,  1.,  0.],
       [ 0.,  2., -1.,  0., -2.,  0.],
       [-2.,  1.,  0.,  0., -1.,  0.],
       [-2., -2., -1., -1., -1.,  0.]])

In [50]:
#6. Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.abs() function to compute the absolute value of each element in the array.
arr=np.abs(np.random.randn(3,3))
arr

array([[1.07635201, 0.69912263, 0.50991482],
       [0.22718168, 1.14499494, 0.91503346],
       [0.83827768, 0.28310762, 0.60722717]])

In [51]:
np.abs(arr)

array([[1.07635201, 0.69912263, 0.50991482],
       [0.22718168, 1.14499494, 0.91503346],
       [0.83827768, 0.28310762, 0.60722717]])

In [19]:
#7. Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.power() function to raise each element in the array to the power of 2.
np.power(np.random.randn(4,4),2)

array([[6.43396543e-01, 5.92809120e+00, 1.55346087e-04, 2.69665189e-02],
       [5.34143701e-01, 3.29432508e-02, 2.11370720e-03, 7.55094392e-01],
       [1.67050293e-01, 1.04650081e-06, 1.57331120e-01, 1.55648240e-01],
       [9.91391879e-01, 1.07674127e-01, 1.95436540e+00, 4.36945484e-01]])

In [23]:
#8. Create a NumPy array with 5 random integers between 1 and 10. Use the maximum function to find the largest element in the array.
arr=np.random.randint(1,11,size=5)
arr

array([5, 9, 1, 6, 6])

In [24]:
np.max(arr)

9

In [36]:
#9. Create a NumPy array with 10 random floating-point numbers between 0 and 1. Use the round function to round each element to the nearest integer.
arr=np.random.rand(10)
arr

array([0.20002495, 0.8012938 , 0.25873225, 0.99032351, 0.40702024,
       0.79309077, 0.35613289, 0.34054295, 0.65098179, 0.35268985])

In [37]:
np.round(arr)

array([0., 1., 0., 1., 0., 1., 0., 0., 1., 0.])

In [32]:
#10. Create a NumPy array with 7 random integers between 1 and 100. Use the argmax function to find the index of the largest element in the array.
a=np.random.randint(1,100,size=7,dtype=int)
a

array([65, 51, 38, 16, 98, 32, 30])

In [33]:
np.array(a).argmax()

4

In [41]:
#11. Create two NumPy arrays with the same shape, each filled with random integers between 1 and Use the add function to add the two arrays together element-wise
a=np.random.randint(1,10,size=7,dtype=int)
b=np.random.randint(1,100,size=7,dtype=int)
a


array([1, 4, 3, 9, 9, 4, 4])

In [42]:
b

array([47, 31, 84, 49, 82, 22, 44])

In [43]:
a+b

array([48, 35, 87, 58, 91, 26, 48])

In [44]:
np.add(a,b)

array([48, 35, 87, 58, 91, 26, 48])

In [48]:
#12. Create a NumPy array with 12 random integers between 0 and 100. Use the clip function to limit the values in the array to a range between 10 and 90
arr=np.random.randint(1,100,size=12,dtype=int)
arr

array([27, 30,  8, 26, 97, 17, 81, 99, 10, 88, 89, 20])

In [49]:
np.clip(arr,10,90)

array([27, 30, 10, 26, 90, 17, 81, 90, 10, 88, 89, 20])