In [1]:
#Numpy (Array Processing)

In [2]:
import numpy as np

In [4]:
#1. Create a NumPy array with 10 random integers between 0 and 100
a=np.random.randint(0,100,size=10)
a

array([ 9, 62, 28, 80, 63, 59, 52, 58, 67, 70])

In [7]:
#2. Use the np.where() function to create a new array with the same shape as the previous one, where values less than 50 are replaced with -1 and values greater than or equal to 50 arereplaced with 1.
np.where(a< 50,-1,1)


array([-1,  1, -1,  1,  1,  1,  1,  1,  1,  1])

In [8]:
#3. Calculate the mean, median, and standard deviation of the original array
np.mean(a)

54.8

In [9]:
np.median(a)

60.5

In [10]:
np.std(a)

19.96396754154845

In [12]:
#4. Create a boolean array that is True where the values in the original array are even, and False otherwise
np.where(a%2==0,'TRUE','FALSE')

array(['FALSE', 'TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE', 'TRUE',
       'FALSE', 'TRUE'], dtype='<U5')

In [13]:
#5. Sort the original array in ascending order.
np.sort(a)

array([ 9, 28, 52, 58, 59, 62, 63, 67, 70, 80])

In [14]:
#6. Find the unique values in the original array.
np.unique(a)

array([ 9, 28, 52, 58, 59, 62, 63, 67, 70, 80])

In [19]:
#7. Use the np.in1d() function to create a boolean array indicating which elements of the original
#array are also present in a new array with 5 random integers between 0 and 100.
b=np.random.randint(0,100,size=5)
b

array([95, 96, 90, 84, 92])

In [20]:
np.in1d(a,b)

array([False, False, False, False, False, False, False, False, False,
       False])

In [22]:
#8. Save the original array to a text file named "my_array.txt" using the np.savetxt() function
np.savetxt('my_array_.txt',a,delimiter=',')