In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,5)

In [3]:
arr

array([[-1.49349742,  0.73321569, -1.13774705,  1.66048726,  0.44390176],
       [ 0.46231098,  0.94782056,  0.45283894, -0.7139719 , -1.19601805],
       [-0.22633185, -1.65595865,  0.48175788,  1.28940205, -0.08450067],
       [-1.64862769,  0.28129272, -0.06995946,  0.43752624, -1.18684388],
       [-0.4295647 ,  0.91746795, -2.66030339, -0.60449493,  1.90697335]])

In [4]:
2+1.5*(arr)

array([[-0.24024613,  3.09982354,  0.29337943,  4.49073089,  2.66585264],
       [ 2.69346647,  3.42173084,  2.67925842,  0.92904214,  0.20597293],
       [ 1.66050223, -0.48393797,  2.72263682,  3.93410308,  1.873249  ],
       [-0.47294153,  2.42193909,  1.89506081,  2.65628937,  0.21973418],
       [ 1.35565295,  3.37620193, -1.99045508,  1.09325761,  4.86046003]])

In [5]:
A=np.array([-2,5,4,-8,0])
a=np.sort(A) #Ascending

In [6]:
a

array([-8, -2,  0,  4,  5])

In [7]:
np.flip(a) #Descending

array([ 5,  4,  0, -2, -8])