In [1]:
import numpy as np

In [2]:
l1=[1,2,3,4]

In [3]:
arry1=np.array(l1)

In [7]:
arry1


array([1, 2, 3, 4])

In [8]:
l2=[11,22,33,44] #another list
l2

[11, 22, 33, 44]

In [9]:
l=[l1,l2] #combining two lists
l 

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [10]:
array_2D=np.array(l) #2D array
array_2D

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
array_2D.shape 

(2, 4)

In [12]:
array_2D.dtype

dtype('int32')

In [13]:
np.zeros(3,'int')

array([0, 0, 0])

In [14]:
 np.ones(3) 

array([1., 1., 1.])

In [15]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros(3)
np.empty(3) 

array([0., 0., 0.])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [20]:
np.arange(0,20,-2)

array([], dtype=int32)

In [21]:
np.arange(0,-20,-2)

array([  0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18])

In [22]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
np.empty(3) 

array([0., 0., 0.])

In [27]:
 np.ones(3,'int') 

array([1, 1, 1])

In [32]:
np.eye(5, k=2, dtype=int)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.eye(3, dtype=complex) * (1 + 1j)

array([[1.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+1.j]])

In [36]:
np.eye(3) *(0.6)

array([[0.6, 0. , 0. ],
       [0. , 0.6, 0. ],
       [0. , 0. , 0.6]])

In [37]:
np.empty(3) 

array([0.6, 0.6, 0.6])

In [38]:
 np.ones(3) 
np.empty(3)   

array([1., 1., 1.])